### ISSUE TITLE
README suggestions

### ISSUE THREAD

**Issue by krismz** [SCIInstitute/SCI-Solver_Eikonal#10]
I ran through the build, example and test instructions on Mac OSX 10.11, GeForce GT 650M, CUDA 7.5 and have the following comments/recommendations:
- Add a line mentioning where results from the examples can be found, and perhaps even describe an easy way to view them.
- 3D Eikonal Homogeneous Sphere example, the input should be ../src/test/test_data/sphere8092
- 3D Eikonal Homogeneous Cube example, ../src/test/test_data/cube_matrices.txt doesn't exist
  (This example fails for me, but I see a clear error from cudaCheckError that it's out of memory)
- Add a line in the Testing instructions to say "make test" after doing the cmake configuration, and perhaps even describe where to find the test log file

**Comment by brigb123** [comment]
all completed via 502eb7bd1a09eb9794636b7097e2ae6f013746cc
334588264564d390e2454e98762bff4891c04491
a73a42743e797cff5cae1af0481c7507a37e379b
