### ISSUE TITLE
Test 4 fails

### ISSUE THREAD

**Issue by krismz** [SCIInstitute/SCI-Solver_Eikonal#11]
On Mac OSX 10.11 with GeForce GT 650M and CUDA 7.5, I see the following log output for test 4 which fails (all other tests pass):

4/9 Testing: 2D-improve
4/9 Test: 2D-improve
Command: "/Users/krismz/Software/SCI-Solver_Eikonal/build/test/bin/2D-improve"
Directory: /Users/krismz/Software/SCI-Solver_Eikonal/build/test/2d
"2D-improve" start time: May 04 10:05 MDT
## Output:

Running main() from gtest_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from Improve2D
[ RUN      ] Improve2D.DecreaseRMSError
NO cross edge!!! Maybe a hole!!
NO cross edge!!! Maybe a hole!!
NO cross edge!!! Maybe a hole!!
NO cross edge!!! Maybe a hole!!
NO cross edge!!! Maybe a hole!!
NO cross edge!!! Maybe a hole!!
NO cross edge!!! Maybe a hole!!
NO cross edge!!! Maybe a hole!!
/Users/krismz/Software/SCI-Solver_Eikonal/src/test/2d/2D-improve.cc:105: Failure
Value of: rmsError[i - 1] > rmsError[i]
  Actual: false
Expected: true
[  FAILED  ] Improve2D.DecreaseRMSError (513 ms)
[----------] 1 test from Improve2D (513 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (513 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] Improve2D.DecreaseRMSError

 1 FAILED TEST
<end of output>
## Test time =   0.54 sec

Test Failed.
"2D-improve" end time: May 04 10:05 MDT
## "2D-improve" time elapsed: 00:00:00

`

**Comment by brigb123** [comment]
This is a result of #6 . depending on the architecture, the # of blocks, and the weather, some 2D tests sometimes fail. I don't know if there is time or motivation to investigate this further. These tests work 80% of the time on my windows and opensuse machines.
