### ISSUE TITLE
CPU version？

### ISSUE THREAD

**Issue by nuaawqf** [SCIInstitute/SCI-Solver_Eikonal#14]
Hi:

Do you support running only on CPU? I don't have GPU on my laptop. How should I port GPU version to CPU version? Thanks.

Regards,
Qifeng.

**Comment by GPayne** [comment]
Hi Qifeng,
This solver is written only for a GPU.
Concerning a port to a CPU version, I would suggest searching online for general methods to convert from GPU to CPU. The solver uses multiple parallel threads, and it is possible to convert to running multiple threads on CPU, although this would be much slower.
